//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YOYPlayer.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YOYPlayer.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTER.
        /// </summary>
        public static string Auth_btnEnter_Content {
            get {
                return ResourceManager.GetString("Auth_btnEnter_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string Auth_link_Text {
            get {
                return ResourceManager.GetString("Auth_link_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, the validity time has expired, it is necessary to re-login.
        /// </summary>
        public static string Auth_Message_Expired {
            get {
                return ResourceManager.GetString("Auth_Message_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lo sentimos, el usuario o la contraseña con incorrectas, intente nuevamente.
        /// </summary>
        public static string Auth_Message_WrongCredentials {
            get {
                return ResourceManager.GetString("Auth_Message_WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Session.
        /// </summary>
        public static string Auth_tblSession_Text {
            get {
                return ResourceManager.GetString("Auth_tblSession_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Auth_tbxLogin_Hint {
            get {
                return ResourceManager.GetString("Auth_tbxLogin_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Auth_tbxPass_Hint {
            get {
                return ResourceManager.GetString("Auth_tbxPass_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUE.
        /// </summary>
        public static string Files_btnRegistration_Content {
            get {
                return ResourceManager.GetString("Files_btnRegistration_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branche.
        /// </summary>
        public static string Files_cbxBranche_Hint {
            get {
                return ResourceManager.GetString("Files_cbxBranche_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commerce.
        /// </summary>
        public static string Files_cbxCommerce_Hint {
            get {
                return ResourceManager.GetString("Files_cbxCommerce_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Files_cbxDepartment_Hint {
            get {
                return ResourceManager.GetString("Files_cbxDepartment_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your location.
        /// </summary>
        public static string Files_tblSubtitle_Text {
            get {
                return ResourceManager.GetString("Files_tblSubtitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Files_tblTitle_Text {
            get {
                return ResourceManager.GetString("Files_tblTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Logs_tblDateTitle_Text {
            get {
                return ResourceManager.GetString("Logs_tblDateTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour:.
        /// </summary>
        public static string Logs_tblHourTitle_Text {
            get {
                return ResourceManager.GetString("Logs_tblHourTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binnacle.
        /// </summary>
        public static string Logs_tblTitle_Text {
            get {
                return ResourceManager.GetString("Logs_tblTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hemos podido recuperar la información solicitada.
        /// </summary>
        public static string Response_Error {
            get {
                return ResourceManager.GetString("Response_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE USER.
        /// </summary>
        public static string Status_btnExit_Content {
            get {
                return ResourceManager.GetString("Status_btnExit_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE LOCATION.
        /// </summary>
        public static string Status_btnFile_Content {
            get {
                return ResourceManager.GetString("Status_btnFile_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICS.
        /// </summary>
        public static string Status_btnLogs_Content {
            get {
                return ResourceManager.GetString("Status_btnLogs_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Status_lblActive_Text {
            get {
                return ResourceManager.GetString("Status_lblActive_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Status_lblNoActive_Text {
            get {
                return ResourceManager.GetString("Status_lblNoActive_Text", resourceCulture);
            }
        }
    }
}
